version: "3.9"
services:

  app:
    build:
      context: .
      # allow Dockerfile to copy files from shared folder
      additional_contexts:
        shared: ../../shared
    ports: 
      - 8080:8080
    restart: on-failure
    volumes:
    - ai-learning-llm-cache:/llm_cache

volumes:
  # You must manually create this volume before running!
  ai-learning-llm-cache:
    external: true